// Generated by scripts/build-extension-core.cjs; edit mobile/src/core sources.
(function(root) {
const modules = {};
modules['./TitleText'] = (() => { const exports = {}; const require = name => modules[name];
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DESCRIPTION_WEIGHT = void 0;
exports.titleParts = titleParts;
// Spaced hyphens separate descriptions; word hyphens (sugar-free, cold-pressed)
// remain part of the product name. Typography dashes also separate descriptions.
function titleParts(title) {
    const match = /\s+-\s+|\s*[–—]\s*/.exec(title || '');
    if (!match)
        return { name: title || '', description: '' };
    return { name: title.slice(0, match.index), description: title.slice(match.index + match[0].length) };
}
exports.DESCRIPTION_WEIGHT = 0.25;

return exports; })();
modules['./ProductComparison'] = (() => { const exports = {}; const require = name => modules[name];
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.matchScore = matchScore;
exports.compareProduct = compareProduct;
exports.refreshComparison = refreshComparison;
exports.parseComparisonPrice = parseComparisonPrice;
exports.sizePriceSuggestion = sizePriceSuggestion;
exports.editComparisonCell = editComparisonCell;
exports.reshuffleMatches = reshuffleMatches;
const TitleText_1 = require("./TitleText");
const ignored = new Set(['pack', 'of', 'the', 'and', 'with', 'fresh', 'buy', 'online', 'g', 'gm', 'kg', 'ml', 'l', 'instant', 'breakfast', 'cereal']);
const words = (text) => (text || '').toLowerCase()
    .replace(/\bcooks?\s+in\s+\d+\s*(?:minutes?|mins?)/g, ' ')
    .replace(/\d+(?:\.\d+)?\s*(?:kgs?|kilograms?|grams?|gms?|g|ml|millilitres?|milliliters?|litres?|liters?|ltrs?|l)\b/g, ' ')
    .replace(/[^a-z0-9]+/g, ' ').split(' ')
    .filter(word => word.length > 1 && !ignored.has(word) && !/^\d+$/.test(word));
function size(item) {
    const text = `${item.quantity || ''} ${item.title}`.toLowerCase();
    const match = text.match(/(\d+(?:\.\d+)?)\s*(kgs?|kilograms?|grams?|gms?|g|ml|millilitres?|milliliters?|litres?|liters?|ltrs?|l)\b/);
    if (!match)
        return null;
    const unit = match[2];
    const value = Number(match[1]) * (/^kg|^kilo|^l(?!m)/.test(unit) ? 1000 : 1);
    const count = text.match(/pack\s*of\s*(\d+)\b/) || text.match(/(\d+)\s*[x×]\s*\d+(?:\.\d+)?\s*(?:kg|g|ml|l)\b/)
        || text.match(/\d+(?:\.\d+)?\s*(?:kg|g|ml|l)\s*[x×]\s*(\d+)\b/);
    return `${/^(?:ml|milli|l)/.test(unit) ? 'volume' : 'weight'}:${value}:${count ? Number(count[1]) : 1}`;
}
function titleBrand(title) {
    const brand = title.toLowerCase().match(/\b(quaker|saffola|pintola|yogabar|bagrry'?s|kellogg'?s|amul|milky\s+mist|mother\s+dairy)\b/);
    return brand ? brand[1].replace(/['\s]/g, '') : '';
}
// Titles establish relevance; size and price rank the plausible candidates.
// Missing or conflicting scraped sizes are not a hard exclusion.
function matchScore(anchor, candidate) {
    if (!(candidate.price > 0))
        return null;
    const aSize = size(anchor), bSize = size(candidate);
    const aBrand = words(anchor.brand || '').join(' '), bBrand = words(candidate.brand || '').join(' ');
    // Current scrapers sometimes put the store name in the brand field.
    const known = (brand) => brand && !['unknown', 'generic', 'unbranded', 'na',
        'swiggy instamart', 'instamart', 'zepto', 'blinkit', 'amazon in', 'amazon now tez', 'flipkart'].includes(brand);
    if (known(aBrand) && known(bBrand) && aBrand !== bBrand)
        return null;
    const inferredA = titleBrand(anchor.title), inferredB = titleBrand(candidate.title);
    if (inferredA && inferredB && inferredA !== inferredB)
        return null;
    const a = new Set(words(anchor.title)), b = new Set(words(candidate.title));
    const weightedWords = (title, stripAliases) => {
        const parts = (0, TitleText_1.titleParts)(stripAliases ? title.replace(/\([^)]*\)/g, ' ') : title);
        const weights = new Map(words(parts.description).map(word => [word, TitleText_1.DESCRIPTION_WEIGHT]));
        words(parts.name).forEach(word => weights.set(word, 1));
        return weights;
    };
    const variants = ['salted', 'unsalted', 'organic', 'skimmed', 'toned', 'flavoured', 'masala', 'spring', 'sambar', 'powder', 'protein', 'fat', 'phool', 'doda', 'dodi'];
    if ((a.has('salted') && b.has('unsalted')) || (a.has('unsalted') && b.has('salted')))
        return null;
    if (['masala', 'spring', 'sambar', 'powder', 'phool', 'doda', 'dodi', 'cookies', 'spread'].some(word => a.has(word) !== b.has(word)))
        return null;
    const processed = ['chips', 'wafers', 'fries', 'sticks', 'starch', 'snacks'];
    if (processed.some(word => a.has(word)) !== processed.some(word => b.has(word)))
        return null;
    const variantPenalty = variants.filter(word => a.has(word) !== b.has(word)).length * 15;
    const overlap = (left, right) => {
        const common = [...left].reduce((sum, [word, weight]) => sum + Math.min(weight, right.get(word) || 0), 0);
        const leftTotal = [...left.values()].reduce((sum, weight) => sum + weight, 0);
        const rightTotal = [...right.values()].reduce((sum, weight) => sum + weight, 0);
        return { common, coverage: common / Math.max(1, Math.min(leftTotal, rightTotal)),
            similarity: common / Math.max(1, leftTotal + rightTotal - common) };
    };
    const full = overlap(weightedWords(anchor.title, false), weightedWords(candidate.title, false));
    const primary = overlap(weightedWords(anchor.title, true), weightedWords(candidate.title, true));
    const { common, coverage, similarity } = primary.similarity > full.similarity ? primary : full;
    if (!common || coverage < 0.6 || similarity < 0.35)
        return null;
    const priceDistance = Math.abs(candidate.price - anchor.price) / Math.max(anchor.price, candidate.price, 1);
    const sizeBonus = aSize && bSize ? (aSize === bSize ? 25 : -35) : 0;
    return similarity * 100 + coverage * 30 + sizeBonus - variantPenalty - (a.has('baby') !== b.has('baby') ? 25 : 0)
        + (known(aBrand) && aBrand === bBrand ? 20 : 0) + (1 - priceDistance) * 80;
}
function compareProduct(anchorStore, anchor, stores, query) {
    const cells = {};
    let cheapestPrice = Infinity;
    let cheapestStoreId = null;
    for (const store of stores) {
        let item = store.platformId === anchorStore.platformId ? anchor : null;
        if (!item) {
            let best = -Infinity;
            for (const candidate of store.candidates?.length ? store.candidates : store.item ? [store.item] : []) {
                const score = matchScore(anchor, candidate);
                if (score !== null && score > best) {
                    best = score;
                    item = candidate;
                }
            }
        }
        const price = item?.price || 0;
        const anchorSize = size(anchor), candidateSize = item ? size(item) : null;
        const comparisonKind = anchorSize && candidateSize ? (anchorSize === candidateSize ? 'same_pack' : 'different_pack') : 'size_unknown';
        const priceDifferencePercent = anchor.price > 0 ? Math.abs(price - anchor.price) / anchor.price * 100 : 0;
        const isComparable = price > 0 && Math.abs(Math.round(price * 100) - Math.round(anchor.price * 100)) * 100 <= Math.round(anchor.price * 100) * 20;
        cells[store.platformId] = {
            platformId: store.platformId, platformName: store.platformName,
            isAvailable: price > 0, isComparable, comparisonKind, priceDifferencePercent, item,
            candidates: [...(store.candidates?.length ? store.candidates : store.item ? [store.item] : [])],
            price, mrp: item?.mrp || price,
            productUrl: item?.productUrl || store.searchUrl || store.globalUrl || '#', isCheapestInRow: false
        };
        if (isComparable && price < cheapestPrice) {
            cheapestPrice = price;
            cheapestStoreId = store.platformId;
        }
    }
    Object.values(cells).forEach(cell => { cell.isCheapestInRow = cell.isComparable === true && cell.price === cheapestPrice; });
    return refreshComparison({
        id: `comparison_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`, query: anchor.title,
        selectionKey: `${anchor.title}|${anchor.quantity}|${anchor.brand}`.toLowerCase(),
        searchQuery: query, anchorStoreId: anchorStore.platformId, anchorItem: anchor, addedAt: Date.now(), stores: cells,
        cheapestPrice: Number.isFinite(cheapestPrice) ? cheapestPrice : 0, cheapestStoreId
    });
}
function refreshComparison(row) {
    const anchor = row.anchorItem || (row.anchorStoreId ? row.stores[row.anchorStoreId]?.item : null);
    if (!anchor)
        return row;
    const anchorSize = size(anchor);
    const stores = { ...row.stores };
    let cheapestPrice = Infinity, cheapestStoreId = null;
    for (const savedCell of Object.values(stores)) {
        // Migrate an earlier manually accepted estimate back to its pack price.
        const cell = savedCell.sizeAdjustment ? { ...savedCell, price: savedCell.sizeAdjustment.sourcePrice,
            item: savedCell.item ? { ...savedCell.item, price: savedCell.sizeAdjustment.sourcePrice } : null,
            originalPrice: savedCell.originalPrice === savedCell.sizeAdjustment.sourcePrice ? undefined : savedCell.originalPrice,
            sizeAdjustment: undefined } : savedCell;
        const estimate = sizePriceSuggestion(row, cell);
        const effectivePrice = estimate?.price ?? cell.price;
        const candidateSize = cell.item ? size(cell.item) : null;
        const comparisonKind = anchorSize && candidateSize ? (anchorSize === candidateSize ? 'same_pack' : 'different_pack') : 'size_unknown';
        const priceDifferencePercent = anchor.price > 0 ? Math.abs(effectivePrice - anchor.price) / anchor.price * 100 : 0;
        const withinPriceRange = Math.abs(Math.round(effectivePrice * 100) - Math.round(anchor.price * 100)) * 100 <= Math.round(anchor.price * 100) * 20;
        const isComparable = cell.isAvailable && cell.price > 0 && (cell.includeInTotals === true || withinPriceRange);
        stores[cell.platformId] = { ...cell, effectivePrice, effectiveQuantity: estimate?.anchorQuantity, comparisonKind, priceDifferencePercent, isComparable, isCheapestInRow: false };
        if (isComparable && effectivePrice < cheapestPrice) {
            cheapestPrice = effectivePrice;
            cheapestStoreId = cell.platformId;
        }
    }
    Object.values(stores).forEach(cell => { cell.isCheapestInRow = cell.isComparable === true && cell.effectivePrice === cheapestPrice; });
    return { ...row, stores, cheapestStoreId, cheapestPrice: Number.isFinite(cheapestPrice) ? cheapestPrice : 0 };
}
function parseComparisonPrice(input) {
    const clean = input.replace(/[₹,\s]/g, '');
    if (!/^\d+(?:\.\d{1,2})?$/.test(clean))
        return null;
    const price = Number(clean);
    return Number.isFinite(price) && price > 0 && price <= 500000 ? price : null;
}
function sizePriceSuggestion(row, cell) {
    const anchor = row.anchorItem || (row.anchorStoreId ? row.stores[row.anchorStoreId]?.item : null);
    if (!anchor || !cell.item || !cell.isAvailable || cell.sizeAdjustment || !(anchor.price > 0) || !(cell.price > 0) ||
        Math.abs(Math.round(cell.price * 100) - Math.round(anchor.price * 100)) * 100 <= Math.round(anchor.price * 100) * 20)
        return null;
    const measured = (item) => {
        const quantity = size({ ...item, title: '' })?.split(':'), title = size({ ...item, quantity: '' })?.split(':');
        if (!quantity)
            return title;
        if (title && Number(title[2]) > 1) {
            if (quantity[0] !== title[0])
                return null;
            const total = Number(title[1]) * Number(title[2]);
            // Quantity may already be the total pack weight. Do not multiply twice.
            if (Number(quantity[1]) * Number(quantity[2]) === total)
                return quantity;
            if (Number(quantity[2]) === 1 && Number(quantity[1]) === Number(title[1]))
                return title;
            return null;
        }
        return quantity;
    };
    const a = measured(anchor), b = measured(cell.item);
    if (!a || !b || a[0] !== b[0])
        return null;
    const anchorAmount = Number(a[1]) * Number(a[2]), storeAmount = Number(b[1]) * Number(b[2]);
    if (!(anchorAmount > 0) || !(storeAmount > 0) || !Number.isFinite(anchorAmount + storeAmount) || anchorAmount === storeAmount)
        return null;
    const price = Math.round(cell.price / storeAmount * anchorAmount * 100) / 100;
    if (!Number.isFinite(price) || price <= 0 || price > 500000 || price === cell.price)
        return null;
    const unit = a[0] === 'weight' ? 'g' : 'ml';
    return { price, sourcePrice: cell.price, anchorQuantity: `${anchorAmount} ${unit}`, storeQuantity: `${storeAmount} ${unit}` };
}
function editComparisonCell(row, platform, edit) {
    const cell = refreshComparison(row).stores[platform];
    if (!cell)
        return row;
    let updated;
    if (edit.kind === 'swap') {
        const item = cell.candidates?.[edit.index];
        if (!item || !(item.price > 0))
            return row;
        updated = { ...cell, item: { ...item }, price: item.price, mrp: item.mrp || item.price,
            productUrl: item.productUrl || cell.productUrl, isAvailable: true, manuallySelected: true, originalPrice: undefined, sizeAdjustment: undefined, includeInTotals: undefined };
    }
    else if (edit.kind === 'price') {
        if (!cell.item || !Number.isFinite(edit.price) || edit.price <= 0 || edit.price > 500000)
            return row;
        updated = { ...cell, price: edit.price, item: { ...cell.item, price: edit.price },
            originalPrice: cell.originalPrice ?? cell.price, sizeAdjustment: undefined };
    }
    else if (edit.kind === 'include') {
        if (!cell.isAvailable || !cell.item)
            return row;
        updated = { ...cell, includeInTotals: true };
    }
    else {
        updated = { ...cell, item: null, price: 0, isAvailable: false, originalPrice: undefined, sizeAdjustment: undefined, manuallySelected: false, includeInTotals: undefined };
    }
    const anchorItem = row.anchorItem || (row.anchorStoreId ? row.stores[row.anchorStoreId]?.item : null) || undefined;
    return refreshComparison({ ...row, anchorItem, stores: { ...row.stores, [platform]: updated } });
}
function reshuffleMatches(stores, row) {
    const anchor = row.anchorStoreId ? row.stores[row.anchorStoreId]?.item : null;
    if (!anchor)
        return stores;
    return stores.map(store => {
        const cell = row.stores[store.platformId];
        const candidates = [...(store.candidates?.length ? store.candidates : store.item ? [store.item] : [])];
        candidates.sort((a, b) => {
            if (a === cell?.item)
                return -1;
            if (b === cell?.item)
                return 1;
            return (matchScore(anchor, b) ?? -1) - (matchScore(anchor, a) ?? -1);
        });
        return { ...store, candidates, selectedIndex: cell?.item ? 0 : undefined, comparisonMatch: !!cell?.item };
    });
}

return exports; })();
modules['./ProductSearch'] = (() => { const exports = {}; const require = name => modules[name];
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.productSearchTitle = productSearchTitle;
const normalizeSize = (text) => text.toLowerCase().replace(/(\d+(?:\.\d+)?)\s*(kilograms?|kgs?|grams?|gms?|g|millilitres?|milliliters?|ml|litres?|liters?|ltrs?|l)\b/g, (_, amount, unit) => {
    const volume = /^(?:ml|milli|l)/.test(unit);
    const factor = /^(?:kg|kilo|l(?!m))/.test(unit) ? 1000 : 1;
    return `${volume ? 'volume' : 'weight'}{${Number(amount) * factor}}`;
}).replace(/[\s()|,]/g, '');
function productSearchTitle(item) {
    const title = item.title.trim(), quantity = (item.quantity || '').trim();
    if (!quantity || normalizeSize(title).includes(normalizeSize(quantity)))
        return title;
    return `${title} ${quantity}`;
}

return exports; })();
modules['./SearchHistory'] = (() => { const exports = {}; const require = name => modules[name];
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SEARCH_HISTORY_KEY = void 0;
exports.normalizeSearchHistory = normalizeSearchHistory;
exports.historyMatches = historyMatches;
exports.SEARCH_HISTORY_KEY = 'lowp_search_history_v1';
const clean = (value) => value.trim().replace(/\s+/g, ' ');
const key = (value) => clean(value).toLowerCase();
// Newest first; case and repeated whitespace do not create duplicate entries.
function normalizeSearchHistory(value) {
    if (!Array.isArray(value))
        return [];
    const seen = new Set();
    const result = [];
    for (const entry of value) {
        if (typeof entry !== 'string' || !clean(entry) || seen.has(key(entry)))
            continue;
        seen.add(key(entry));
        result.push(clean(entry));
        if (result.length === 1000)
            break;
    }
    return result;
}
function historyMatches(history, query) {
    const term = key(query);
    if (!term)
        return history.slice(0, 10);
    const matches = history.filter(entry => key(entry).includes(term));
    // Exact/prefix matches first, then other matches, newest first within each group.
    const rank = (entry) => key(entry) === term ? 0 : key(entry).startsWith(term) ? 1 : 2;
    return matches.sort((a, b) => rank(a) - rank(b)).slice(0, 10);
}

return exports; })();
modules['./StoreOffers'] = (() => { const exports = {}; const require = name => modules[name];
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.OFFERS_STORAGE_KEY = void 0;
exports.normalizeOffer = normalizeOffer;
exports.calculateOffer = calculateOffer;
exports.comparisonBaskets = comparisonBaskets;
exports.OFFERS_STORAGE_KEY = 'lowp_store_offers_v1';
const money = (value) => Math.round((value + Number.EPSILON) * 100) / 100;
function normalizeOffer(offer) {
    const tiers = (offer?.tiers || []).filter(tier => Number.isFinite(tier.threshold) && tier.threshold > 0 && Number.isFinite(tier.cashback) && tier.cashback >= 0)
        .sort((a, b) => a.threshold - b.threshold);
    return { cardPercent: Number.isFinite(offer?.cardPercent) ? Math.max(0, Math.min(100, offer.cardPercent)) : 0, tiers };
}
// Milestones use the product subtotal before card discount; only the highest
// eligible cashback is applied, rather than adding every reached level.
function calculateOffer(subtotal, offer) {
    const base = money(Math.max(0, subtotal));
    const { cardPercent, tiers } = normalizeOffer(offer);
    const discount = money(base * cardPercent / 100);
    const payable = money(base - discount);
    const reached = tiers.filter(tier => base >= tier.threshold);
    const cashback = reached.length ? Math.max(...reached.map(tier => tier.cashback)) : 0;
    const next = tiers.find(tier => tier.threshold > base && tier.cashback > cashback);
    return { subtotal: base, cardPercent, discount, payable, cashback,
        effectiveTotal: money(Math.max(0, payable - cashback)),
        reachedThreshold: reached.slice().reverse().find(tier => tier.cashback === cashback)?.threshold,
        next: next ? { ...next, remaining: money(next.threshold - base), additional: money(next.cashback - cashback) } : null };
}
function comparisonBaskets(rows, offers) {
    const ids = [...new Set(rows.flatMap(row => Object.keys(row.stores)))];
    const complete = ids.flatMap(id => {
        const cells = rows.map(row => row.stores[id]);
        if (!rows.length || !cells.every(cell => cell?.isAvailable && cell.isComparable !== false))
            return [];
        return [{ id, name: cells[0].platformName, ...calculateOffer(cells.reduce((sum, cell) => sum + (cell.effectivePrice ?? cell.price), 0), offers[id]) }];
    }).sort((a, b) => a.effectiveTotal - b.effectiveTotal);
    const incomplete = ids.filter(id => !complete.some(store => store.id === id)).map(id => {
        const included = rows.filter(row => row.stores[id]?.isAvailable && row.stores[id].isComparable !== false);
        const missing = rows.filter(row => !row.stores[id]?.isAvailable || row.stores[id].isComparable === false)
            .map(row => ({ title: row.query, excluded: !!row.stores[id]?.isAvailable }));
        const name = rows.find(row => row.stores[id]).stores[id].platformName;
        return { id, name, count: included.length, missing,
            ...calculateOffer(included.reduce((sum, row) => sum + (row.stores[id].effectivePrice ?? row.stores[id].price), 0), offers[id]) };
    });
    return { complete, incomplete };
}

return exports; })();
modules['./MatchingEngine'] = (() => { const exports = {}; const require = name => modules[name];
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MatchingEngine = void 0;
const TitleText_1 = require("./TitleText");
class MatchingEngine {
    static extractQuantity(text) {
        const measure = (text || '').match(/(?:\b\d+\s*[x×]\s*)?\b\d+(?:\.\d+)?\s*(?:kgs?|kilograms?|grams?|gms?|g|ml|millilitres?|milliliters?|litres?|liters?|ltrs?|l)\b(?:\s*[x×]\s*\d+\b|\s*\(?pack\s+of\s+\d+\)?)?/i);
        return measure ? measure[0].replace(/\s+/g, ' ').trim() : '';
    }
    static extractCardQuantity(title, html) {
        const fromTitle = this.extractQuantity(title);
        if (fromTitle)
            return fromTitle;
        // Flipkart often renders the net quantity as a separate short text node.
        // Stay inside the product block and ignore scripts, styles and unit prices.
        const textNodes = html.replace(/<(script|style)\b[^>]*>[\s\S]*?<\/\1>/gi, '')
            .matchAll(/>([^<>]{1,160})</g);
        for (const node of textNodes) {
            const text = node[1].replace(/&nbsp;|&#160;|&#xA0;/gi, ' ').trim();
            const quantity = this.extractQuantity(text);
            if (quantity && text.replace(/[()]/g, '').trim().toLowerCase() === quantity.replace(/[()]/g, '').trim().toLowerCase())
                return quantity;
        }
        return '';
    }
    static extractDetailQuantity(html) {
        const text = html.replace(/<(script|style)\b[^>]*>[\s\S]*?<\/\1>/gi, ' ')
            .replace(/<[^>]+>/g, ' ').replace(/&nbsp;|&#160;|&#xA0;/gi, ' ').replace(/\s+/g, ' ');
        // A labelled specification avoids pulling a size from recommendations.
        const labelled = text.match(/\b(?:Net Quantity|Quantity)\s*[:\-]?\s*(\d+(?:\.\d+)?\s*(?:kgs?|kilograms?|grams?|gms?|g|ml|millilitres?|milliliters?|litres?|liters?|ltrs?|l|pieces?|pcs?))\b/i);
        return labelled ? labelled[1].trim() : '';
    }
    static calculateTotalCost(item) {
        const basePrice = Math.round(item.price);
        const mrp = Math.round(item.mrp || item.price);
        const savings = Math.max(0, mrp - basePrice);
        const discountPercent = mrp > basePrice ? Math.round((savings / mrp) * 100) : 0;
        return {
            basePrice,
            finalPayable: basePrice,
            savings,
            discountPercent
        };
    }
    static cleanSearchTerm(query) {
        if (!query)
            return '';
        let q = query;
        try {
            q = decodeURIComponent(q);
        }
        catch (e) { }
        q = q.replace(/https?:\/\/[^\s]+/g, '');
        q = q.replace(/\b(?:delivery in\s*)?\d+(?:\s*-\s*\d+)?\s*(?:mins?|minutes?|hours?|sec|seconds?)\b/gi, '');
        q = q.replace(/\b(?:fastest delivery|standard delivery|instant delivery|express delivery|free delivery|delivery)\b/gi, '');
        q = q.replace(/[,\-_|+/\\%]+/g, ' ');
        q = q.replace(/\s+/g, ' ').trim();
        return q;
    }
    static scoreRelevance(itemTitle, query, packSize = '') {
        if (!itemTitle || !query || !query.trim())
            return 0;
        const normalize = (str) => (str || '')
            .toLowerCase()
            .replace(/['’`"]/g, '')
            .replace(/[^a-z0-9\s]/g, ' ')
            .replace(/\s+/g, ' ')
            .trim();
        // Rank on BOTH views of the title: the primary name with parenthetical
        // alt names removed ("Potato (Aalugadda)" -> "Potato") keeps ranking
        // focused, while the untouched title still lets users find items by
        // their alternate name ("searching aalugadda"). The better score wins.
        const fullText = normalize(String(itemTitle).replace(/\([^)]*\)/g, ' ') + ' ' + packSize);
        const fullTextAlt = normalize(`${itemTitle} ${packSize}`);
        const parts = (0, TitleText_1.titleParts)(itemTitle);
        const nameText = normalize(parts.name.replace(/\([^)]*\)/g, ' ') + ' ' + packSize);
        const nameTextAlt = normalize(`${parts.name} ${packSize}`);
        const q = normalize(query);
        const queryTokens = q.split(/\s+/).filter((t) => t.length > 0);
        let score = 0;
        let altScore = 0;
        const matchToken = (text, token) => {
            if (text.includes(token))
                return 30;
            if (token.endsWith('s') && token.length > 3 && text.includes(token.slice(0, -1)))
                return 25;
            if (!token.endsWith('s') && text.includes(token + 's'))
                return 25;
            return 0;
        };
        queryTokens.forEach((token) => {
            score += Math.max(matchToken(nameText, token), matchToken(fullText, token) * TitleText_1.DESCRIPTION_WEIGHT);
            altScore += Math.max(matchToken(nameTextAlt, token), matchToken(fullTextAlt, token) * TitleText_1.DESCRIPTION_WEIGHT);
        });
        score = Math.max(score, altScore);
        // Exact-name preference: a product whose PRIMARY name (parentheticals
        // removed) starts with the query ("Onion (...)" for "onion") outranks
        // products that merely contain the word ("Sambar Onion (...)").
        const strippedTitle = normalize(parts.name.replace(/\([^)]*\)/g, ' '));
        if (q && strippedTitle.startsWith(q))
            score += 20;
        // Variety modifiers denote DIFFERENT products ("spring onion",
        // "sambar onion", "green onion" are not generic onions) — rank them
        // below plain matches instead of letting them tie on relevance.
        const VARIETY_MODIFIERS = ['spring', 'sambar', 'green', 'bunch', 'shallot'];
        if (q) {
            const varietyRx = new RegExp('\\b(' + VARIETY_MODIFIERS.join('|') + ')\\s+' + q + '\\b');
            if (varietyRx.test(strippedTitle))
                score -= 15;
        }
        const qtyMatch = query.match(/(\d+(?:\.\d+)?)\s*(l|litre|litres|kg|kgs|g|gm|gms|ml)/i);
        if (qtyMatch) {
            const qNum = parseFloat(qtyMatch[1]);
            const qUnit = qtyMatch[2].toLowerCase().replace(/litre|litres/, 'l').replace(/kgs?/, 'kg').replace(/gms?/, 'g');
            const targetQtyStr = `${qNum} ${qUnit}`;
            const targetQtyCompact = `${qNum}${qUnit}`;
            if (fullText.includes(targetQtyStr) || fullText.includes(targetQtyCompact)) {
                score += 40;
            }
            else {
                const candQtyMatch = fullText.match(/(\d+(?:\.\d+)?)\s*(l|litre|litres|kg|kgs|g|gm|gms|ml)/i);
                if (candQtyMatch) {
                    const cNum = parseFloat(candQtyMatch[1]);
                    const cUnit = candQtyMatch[2].toLowerCase().replace(/litre|litres/, 'l').replace(/kgs?/, 'kg').replace(/gms?/, 'g');
                    if (cNum !== qNum || cUnit !== qUnit)
                        score -= 40;
                }
            }
        }
        if (queryTokens.length > 0 && fullText.includes(queryTokens[0])) {
            score += nameText.includes(queryTokens[0]) ? 25 : 25 * TitleText_1.DESCRIPTION_WEIGHT;
        }
        return score;
    }
    static applyTitleLengthBonus(candidates, query) {
        if (!candidates || candidates.length <= 1 || !query)
            return candidates;
        const cleanQ = typeof query === "string" ? query.trim() : "";
        const qLen = cleanQ.length;
        if (qLen === 0)
            return candidates;
        const topN = candidates.slice(0, 3);
        const sortedByLenDiff = topN
            .map((item) => ({
            item,
            diff: Math.abs((0, TitleText_1.titleParts)(item.title || '').name.trim().length - qLen)
        }))
            .sort((a, b) => a.diff - b.diff);
        if (sortedByLenDiff[0]) {
            sortedByLenDiff[0].item._score = (sortedByLenDiff[0].item._score || 0) + 20;
            if (typeof sortedByLenDiff[0].item.score === "number") {
                sortedByLenDiff[0].item.score += 20;
            }
        }
        if (sortedByLenDiff[1]) {
            sortedByLenDiff[1].item._score = (sortedByLenDiff[1].item._score || 0) + 10;
            if (typeof sortedByLenDiff[1].item.score === "number") {
                sortedByLenDiff[1].item.score += 10;
            }
        }
        candidates.sort((a, b) => (b._score || b.score || 0) - (a._score || a.score || 0));
        return candidates;
    }
    static annotateBestOffers(results) {
        const availableStores = results.filter((r) => r.isAvailable && r.priceBreakdown && r.priceBreakdown.finalPayable > 0);
        if (availableStores.length === 0) {
            return results.map((r) => ({ ...r, isLowestPrice: false }));
        }
        let minPrice = Infinity;
        for (const store of availableStores) {
            if (store.priceBreakdown.finalPayable < minPrice) {
                minPrice = store.priceBreakdown.finalPayable;
            }
        }
        return results.map((store) => {
            const isLowest = store.isAvailable &&
                store.priceBreakdown !== null &&
                store.priceBreakdown.finalPayable === minPrice;
            return {
                ...store,
                isLowestPrice: isLowest
            };
        });
    }
}
exports.MatchingEngine = MatchingEngine;

return exports; })();
modules['./ProductDetails'] = (() => { const exports = {}; const require = name => modules[name];
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.enrichFlipkartQuantities = enrichFlipkartQuantities;
const MatchingEngine_1 = require("./MatchingEngine");
const quantities = new Map();
async function enrichFlipkartQuantities(items, signal, onQuantity) {
    // At most the three visible candidates, sequentially, without another WebView.
    for (const item of items.slice(0, 3)) {
        if (signal.aborted)
            return;
        if (MatchingEngine_1.MatchingEngine.extractQuantity(item.quantity || '') || !item.productUrl)
            continue;
        let url;
        try {
            url = new URL(item.productUrl.replace(/&amp;/g, '&'));
        }
        catch {
            continue;
        }
        if (url.protocol !== 'https:' || !['www.flipkart.com', 'flipkart.com'].includes(url.hostname) || !url.pathname.includes('/p/'))
            continue;
        const key = `${url.origin}${url.pathname}?pid=${url.searchParams.get('pid') || ''}`;
        const cached = quantities.get(key);
        if (cached && Date.now() - cached.checkedAt < 90000) {
            if (cached.value)
                onQuantity(item, cached.value);
            continue;
        }
        const controller = new AbortController();
        const abort = () => controller.abort();
        signal.addEventListener('abort', abort);
        const timeout = setTimeout(abort, 2500);
        try {
            const response = await fetch(key, { signal: controller.signal });
            if (!response.ok)
                continue;
            const html = await response.text();
            if (signal.aborted || controller.signal.aborted)
                return;
            const quantity = MatchingEngine_1.MatchingEngine.extractDetailQuantity(html);
            if (signal.aborted || controller.signal.aborted)
                return;
            quantities.set(key, { value: quantity, checkedAt: Date.now() });
            if (quantities.size > 60)
                quantities.delete(quantities.keys().next().value);
            if (quantity)
                onQuantity(item, quantity);
        }
        catch { /* Keep the original result when product details are unavailable. */ }
        finally {
            clearTimeout(timeout);
            signal.removeEventListener('abort', abort);
        }
    }
}

return exports; })();
root.LowPCore = Object.assign({}, ...Object.values(modules));
})(globalThis);
